"""add insforge_id to users

Revision ID: 36004e425110
Revises: 0006
Create Date: 2026-04-11 13:18:37.381829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_conversation_id"), "conversation", ["id"], unique=False)
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    op.alter_column(
        "profile",
        "type",
        existing_type=mysql.ENUM("looking_for_flat", "looking_for_roommate"),
        nullable=False,
    )
    op.drop_index(op.f("ix_profile_ciudad"), table_name="profile")
    op.create_index(op.f("ix_profile_city"), "profile", ["city"], unique=False)
    op.create_index(op.f("ix_profile_id"), "profile", ["id"], unique=False)
    op.alter_column(
        "profile_photo", "order", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "profile_photo",
        "is_main",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.create_index(op.f("ix_profile_photo_id"), "profile_photo", ["id"], unique=False)
    op.add_column(
        "user", sa.Column("insforge_id", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "user", "password_hash", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_insforge_id"), "user", ["insforge_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_insforge_id"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.alter_column(
        "user", "password_hash", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.drop_column("user", "insforge_id")
    op.drop_index(op.f("ix_profile_photo_id"), table_name="profile_photo")
    op.alter_column(
        "profile_photo",
        "is_main",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "profile_photo", "order", existing_type=mysql.INTEGER(), nullable=False
    )
    op.drop_index(op.f("ix_profile_id"), table_name="profile")
    op.drop_index(op.f("ix_profile_city"), table_name="profile")
    op.create_index(op.f("ix_profile_ciudad"), "profile", ["city"], unique=False)
    op.alter_column(
        "profile",
        "type",
        existing_type=mysql.ENUM("looking_for_flat", "looking_for_roommate"),
        nullable=True,
    )
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_index(op.f("ix_conversation_id"), table_name="conversation")
    # ### end Alembic commands ###
