"""base_postgres

Revision ID: fd88b8d3e737
Revises:
Create Date: 2026-04-15 21:52:33.396633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd88b8d3e737"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insforge_id", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_insforge_id"), "user", ["insforge_id"], unique=True)
    op.create_table(
        "conversation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user1_id", sa.Integer(), nullable=False),
        sa.Column("user2_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint("user1_id < user2_id", name="check_user1_less_than_user2"),
        sa.ForeignKeyConstraint(["user1_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user2_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user1_id", "user2_id", name="unique_conversation"),
    )
    op.create_index(op.f("ix_conversation_id"), "conversation", ["id"], unique=False)
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("max_budget", sa.Integer(), nullable=True),
        sa.Column("has_pets", sa.Boolean(), nullable=False),
        sa.Column("is_smoker", sa.Boolean(), nullable=False),
        sa.Column(
            "schedule",
            sa.Enum("morning", "afternoon", "night", "flexible", name="scheduleenum"),
            nullable=True,
        ),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column("available_from", sa.Date(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("looking_for_flat", "looking_for_roommate", name="typeenum"),
            nullable=False,
        ),
        sa.Column("room_description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_profile_city"), "profile", ["city"], unique=False)
    op.create_index(op.f("ix_profile_id"), "profile", ["id"], unique=False)
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversation.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sender_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conversation_is_read",
        "message",
        ["conversation_id", "is_read"],
        unique=False,
    )
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    op.create_table(
        "profile_photo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("photo_url", sa.String(length=500), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("is_main", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "order", name="unique_profile_photo_order"),
    )
    op.create_index(
        "idx_profile_order", "profile_photo", ["profile_id", "order"], unique=False
    )
    op.create_index(op.f("ix_profile_photo_id"), "profile_photo", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_photo_id"), table_name="profile_photo")
    op.drop_index("idx_profile_order", table_name="profile_photo")
    op.drop_table("profile_photo")
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_index("idx_conversation_is_read", table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_profile_id"), table_name="profile")
    op.drop_index(op.f("ix_profile_city"), table_name="profile")
    op.drop_table("profile")
    op.drop_index(op.f("ix_conversation_id"), table_name="conversation")
    op.drop_table("conversation")
    op.drop_index(op.f("ix_user_insforge_id"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
